/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jframe;

import JavaUtil.AuthToken;
import JavaUtil.OCIemail;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author guifami
 */
public class EsqueceuSenhaPage extends javax.swing.JFrame {

    /**
     * Creates new form CustomConfirmBox
     */
    
    public EsqueceuSenhaPage(){
        initComponents();
        setLocationRelativeTo(null);
    }
    
    public boolean validaCampos(){
        Usuario.raRec = txt_ra.getText();
        Usuario.emailRec = txt_email.getText();
        if(Usuario.raRec.equals("")){
            CustomDialogBox cdb = new CustomDialogBox("Campo obrigatório: Insira seu Registo.");
            cdb.setVisible(true);
            return false;
        }
        if(Usuario.emailRec.equals("")){
            CustomDialogBox cdb = new CustomDialogBox("Campo obrigatório: Insira seu E-Mail.");
            cdb.setVisible(true);
            return false;
        }
        return true;
    }
    
    public boolean checkRa(){
        boolean isExist = false; 
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection(DBConnection.ip, "", "");            
            PreparedStatement pst = con.prepareStatement("SELECT * FROM USERS WHERE RA = ?");
            pst.setString(1, Usuario.raRec);
            ResultSet rs = pst.executeQuery();
            if(rs.next()){
                isExist = true;
            }else{
                isExist = false;
                CustomDialogBox cdb = new CustomDialogBox("Ra ou Email não compatíveis com o cadastrado.");
                cdb.setVisible(true);
            }
            
        }catch(Exception e){
            e.printStackTrace();
        }
        return isExist;
    }
    
    public boolean checkEmail(){
        boolean isExist = false; 
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection(DBConnection.ip, "", "");            
            PreparedStatement pst = con.prepareStatement("SELECT * FROM USERS WHERE EMAIL = ?");
            pst.setString(1, Usuario.emailRec);
            ResultSet rs = pst.executeQuery();
            if(rs.next()){
                isExist = true;
            }else{
                isExist = false;
                CustomDialogBox cdb = new CustomDialogBox("Ra ou Email não compatíveis com o cadastrado.");
                cdb.setVisible(true);
            }
            
        }catch(Exception e){
            e.printStackTrace();
        }
        return isExist;
    }
    
    public boolean validaRaEEmail(){
        boolean isExist = false; 
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection(DBConnection.ip, "", "");            
            PreparedStatement pst = con.prepareStatement("SELECT EMAIL FROM USERS WHERE RA = ?");
            pst.setString(1, Usuario.raRec);
            ResultSet rs = pst.executeQuery();
            rs.next();
            if(rs.getString(1).equals(Usuario.emailRec))
                isExist = true;
            else{
                isExist = false;
                CustomDialogBox cdb = new CustomDialogBox("Ra ou Email não compatíveis com o cadastrado.");
                cdb.setVisible(true);
            }  
                
        }catch(Exception e){
            e.printStackTrace();
        }
        return isExist;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        txtMsg1 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        kGradientPanel2 = new keeptoo.KGradientPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        kGradientPanel3 = new keeptoo.KGradientPanel();
        ok1 = new rojerusan.RSButtonHover();
        rSLabelImage1 = new rojerusan.RSLabelImage();
        txt_email = new app.bolivia.swing.JCTextField();
        txt_ra = new app.bolivia.swing.JCTextField();
        rSLabelImage2 = new rojerusan.RSLabelImage();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        esqueciSenha2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        esqueciSenha = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(550, 240));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel1.setkEndColor(new java.awt.Color(255, 255, 255));
        kGradientPanel1.setkStartColor(new java.awt.Color(255, 255, 255));
        kGradientPanel1.setMinimumSize(new java.awt.Dimension(550, 275));
        kGradientPanel1.setName(""); // NOI18N
        kGradientPanel1.setPreferredSize(new java.awt.Dimension(550, 275));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtMsg1.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        txtMsg1.setText("Esqueci minha Senha");
        txtMsg1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        kGradientPanel1.add(txtMsg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 270, 50));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Panda Haktoo sem fundo 2.png"))); // NOI18N
        kGradientPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 80, 60));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(34, 57, 121));
        jLabel15.setText("HAKTOO");
        kGradientPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 180, 50));

        kGradientPanel2.setkEndColor(new java.awt.Color(255, 255, 255));
        kGradientPanel2.setkStartColor(new java.awt.Color(255, 255, 255));
        kGradientPanel2.setMinimumSize(new java.awt.Dimension(550, 275));
        kGradientPanel2.setName(""); // NOI18N
        kGradientPanel2.setPreferredSize(new java.awt.Dimension(550, 275));
        kGradientPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Panda Haktoo sem fundo 2.png"))); // NOI18N
        kGradientPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 80, 60));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(34, 57, 121));
        jLabel17.setText("HAKTOO");
        kGradientPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 180, 50));

        kGradientPanel3.setkEndColor(new java.awt.Color(0, 102, 204));
        kGradientPanel3.setkStartColor(new java.awt.Color(0, 102, 204));
        kGradientPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ok1.setBackground(new java.awt.Color(255, 153, 102));
        ok1.setText("Enviar");
        ok1.setColorHover(new java.awt.Color(255, 153, 160));
        ok1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ok1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ok1ActionPerformed(evt);
            }
        });
        kGradientPanel3.add(ok1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, 130, -1));

        rSLabelImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Secured_Letter_50px.png"))); // NOI18N
        kGradientPanel3.add(rSLabelImage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 30, 30));

        txt_email.setBackground(new java.awt.Color(0, 102, 204));
        txt_email.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txt_email.setForeground(new java.awt.Color(255, 255, 255));
        txt_email.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        txt_email.setPhColor(new java.awt.Color(255, 255, 255));
        txt_email.setPlaceholder("Enter your Email:");
        kGradientPanel3.add(txt_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, 290, 30));

        txt_ra.setBackground(new java.awt.Color(0, 102, 204));
        txt_ra.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txt_ra.setForeground(new java.awt.Color(255, 255, 255));
        txt_ra.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        txt_ra.setPhColor(new java.awt.Color(255, 255, 255));
        txt_ra.setPlaceholder("Enter your RA:");
        kGradientPanel3.add(txt_ra, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 290, 30));

        rSLabelImage2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Google_Mobile_50px.png"))); // NOI18N
        kGradientPanel3.add(rSLabelImage2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 30, 30));

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Digite seu E-Mail:");
        kGradientPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, -1, -1));

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Digite seu Registo:");
        kGradientPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, -1, -1));

        esqueciSenha2.setFont(new java.awt.Font("Verdana", 0, 20)); // NOI18N
        esqueciSenha2.setForeground(new java.awt.Color(255, 255, 255));
        esqueciSenha2.setText("Voltar");
        esqueciSenha2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        esqueciSenha2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                esqueciSenha2MouseClicked(evt);
            }
        });
        kGradientPanel3.add(esqueciSenha2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 70, 30));

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 128));
        jLabel5.setText("Você será redirecionado Automaticamente.");
        kGradientPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 50, 360, -1));

        jLabel6.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Ao clicar em \"Enviar\" enviaremos um Código de segurança para o seu Email.");
        kGradientPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 680, 50));

        jLabel7.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Isso pode Demorar alguns Minutos...");
        kGradientPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 680, -1));

        kGradientPanel2.add(kGradientPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 740, 390));

        esqueciSenha.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        esqueciSenha.setText("Esqueci minha Senha");
        esqueciSenha.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        kGradientPanel2.add(esqueciSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 270, 50));

        kGradientPanel1.add(kGradientPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 460));

        getContentPane().add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ok1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ok1ActionPerformed
        if(validaCampos() == true && checkRa() == true && checkEmail() == true && validaRaEEmail() == true){
            try {
                AuthToken at = new AuthToken();
                at.gerarToken();
                OCIemail.executar();
                TokenPage tp = new TokenPage();
                tp.setVisible(true);
                this.dispose();
            } catch (Exception ex) {
                Logger.getLogger(EsqueceuSenhaPage.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_ok1ActionPerformed

    private void esqueciSenha2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_esqueciSenha2MouseClicked
        CustomConfirmBox ccb = new CustomConfirmBox("Você deseja voltar a tela de login?", this);
        ccb.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_esqueciSenha2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EsqueceuSenhaPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EsqueceuSenhaPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EsqueceuSenhaPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EsqueceuSenhaPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EsqueceuSenhaPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel esqueciSenha;
    private javax.swing.JLabel esqueciSenha2;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private keeptoo.KGradientPanel kGradientPanel1;
    private keeptoo.KGradientPanel kGradientPanel2;
    private keeptoo.KGradientPanel kGradientPanel3;
    private rojerusan.RSButtonHover ok1;
    private rojerusan.RSLabelImage rSLabelImage1;
    private rojerusan.RSLabelImage rSLabelImage2;
    private javax.swing.JLabel txtMsg1;
    private app.bolivia.swing.JCTextField txt_email;
    private app.bolivia.swing.JCTextField txt_ra;
    // End of variables declaration//GEN-END:variables
}
